library(skpr)
library(aws.s3)
library(readr)
library(readxl)
library(jsonlite)
library(dplyr)
library(data.table)
library(ggplot2)
library(pwr)
library(tidyverse)
library(hash)
library(shiny)
library(openxlsx)
library(reticulate)
library(DT)
library(shinydashboard)
library(shinyBS)
library(corrplot)
library(httpuv)
library(Rcpp)
library(shinyjs)

source('ui.R')
source('server.R')


shinyApp(ui = ui, server = server, options=list(launch.browser = TRUE))
